name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  Build_push_to_Docker_Hub:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run : |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_TOKEN}} 
      - name: Build 
        run: |
          docker build . -t muguwara1/fever_tokens_app:latest
      - name:
        run: |
          docker push muguwara1/fever_tokens_app:latest
