name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  Build_push_to_Docker_Hub:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run : |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_TOKEN}} 
      - name: Build 
        run: |
          docker build . -t muguwara1/fever_tokens_app:latest
      - name: pushing to docker hub
        run: |
          docker push muguwara1/fever_tokens_app:latest
      - name: Generate ssh key
        run : | 
          ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          cat ~/.ssh/id_ed25519.pub

      

      - name: Deploy on docker swarm
        run : |
          ssh -o StrictHostKeyChecking=no ip172-18-0-30-cpdol9i91nsg009nvep0@direct.labs.play-with-docker.com

      
