name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  Build_push_to_Docker_Hub:
    name: Build and  Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: latest
